name: ctint-science
version: "1.0.0"
summary: ctint-science
description: ctint-science is a continuos time quantum monte carlo solver
confinement: strict
grade: stable
architectures:
  - build-on: [amd64]
    run-on: [amd64]

apps:
  ctint-science:
    command: ctint-science
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/lapack:$SNAP/usr/lib/libblas:$SNAP_LIBRARY_PATH

    plugs:
      - home

parts:
  ctint-science:
    plugin: cmake
    configflags:
      - -DSNAP=ON
    source: https://github.com/ZGCDDoo/ctint-science.git
    source-type: git
    source-branch: master
    build-packages:
      - build-essential
      - make
      - cmake
      - liblapack-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libarmadillo-dev

    stage-packages:
      - liblapack-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libarmadillo-dev

  
