name: ctint-science
version: "1.0.0"
summary: ctint-science
description: ctint-science is a continuos time quantum monte carlo solver
confinement: strict
grade: stable

apps:
  ctint-science:
    command: ctint-science

parts:
  ctint-science:
    plugin: cmake
    configflags:
      - -DSNAP=ON
    source: https://github.com/ZGCDDoo/ctint-science.git
    source-type: git
    source-branch: snapcraft
    build-packages:
      - build-essential
      - make
      - cmake
      - liblapack-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libarmadillo-dev
    # stage-packages:
    #   - liblapack
    #   - libblas
    #   - libarpack
    #   - libarmadillo
    #   - libboost_filesystem
    #   - libboost_system
    #   - libgfortran
    #   - libquadmath
    #   - libsuperlu


  
